# Generated by Django 2.2.4 on 2024-07-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20240706_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_and_supplier_information',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_date_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='handling_and_cooking',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ingredients_and_allergens',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pack_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='por',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_inc_vat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_disclaimer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_packaging_information',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='safety_information',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shelf_dimensions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vat',
        ),
        migrations.AddField(
            model_name='item',
            name='item_details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_image1',
            field=models.ImageField(default=None, upload_to='item_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_image2',
            field=models.ImageField(default=None, upload_to='item_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_image3',
            field=models.ImageField(default=None, upload_to='item_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='specification_image',
            field=models.ImageField(default=None, upload_to='specification_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Subcategory'),
            preserve_default=False,
        ),
    ]
