# Generated by Django 2.2.4 on 2024-07-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20240712_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='design_upload',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Subcategory'),
        ),
    ]
