# Generated by Django 2.2.4 on 2024-07-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20240712_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Subcategory'),
        ),
    ]
